name: Build Windows

on:
  push:
    branches:
      - "!*"
    tags:
      - "v*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Get rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-msvc
          override: true

      - name: Install Wix
        uses: actions/checkout@v2
        with:
          repository: fbarresi/wix
          path: wix

      - name: Install cargo wix
        run: cargo install cargo-wix

      - name: Install FFmpeg
        uses: FedericoCarboni/setup-ffmpeg@v2
        id: setup-ffmpeg

      - name: Install Protoc
        uses: arduino/setup-protoc@v1

      - name: Build Uplink
        run: cargo build --release --package uplink
      
      - name: Build Installer 
        run: cargo wix --package uplink --no-build --nocapture

      - name: Github Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/wix/*.msi