name: Build Linux

on:
  push:
    branches:
      - "!*"
    tags:
      - "**"


jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Github Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ui/Cargo.toml