name: Test Zip

on:
  push:
    branches:
      - "!*"
    tags:
      - "v*"
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Zip Assets
        run:  Compress-Archive -Path .\ui\extra -DestinationPath .\ui\extra\assets.zip
        shell: powershell
