name: Test Zip

on:
  push:
    branches:
      - "!*"
    tags:
      - "v*"
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Zip Assets
        run: $loc = Get-Location; ls -Path $loc #Compress-Archive -LiteralPath ui/extra -DestinationPath ui/extra
        shell: powershell
